name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images for authentication_service
        run: |
          docker build -t azzu097/authentication_service:latest ./authentication_service
          docker push azzu097/authentication_service:latest

      - name: Build and push Docker images for product_service
        run: |
          docker build -t azzu097/product_service:latest ./product_service
          docker push azzu097/product_service:latest

      - name: Build and push Docker images for order_service
        run: |
          docker build -t azzu097/order_service:latest ./order_service
          docker push azzu097/order_service:latest

      - name: Build and push Docker images for payment_service
        run: |
          docker build -t azzu097/payment_service:latest ./payment_service
          docker push azzu097/payment_service:latest

      - name: Build and push Docker images for prometheus
        run: |
          docker build -t azzu097/prometheus:latest ./prometheus
          docker push azzu097/prometheus:latest

      - name: Build and push Docker images for grafana
        run: |
          docker build -t azzu097/grafana:latest ./grafana
          docker push azzu097/grafana:latest

      - name: Deploy to production
        run: |
          docker-compose -f docker-compose.yml up -d
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
